/* A Bison parser, made by GNU Bison 2.3.  */

/* Skeleton interface for Bison's Yacc-like parsers in C

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301, USA.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     ADDRESS = 258,
     ADVANCEDBREPSHAPEREPRESENTATION = 259,
     ADVANCEDFACE = 260,
     AHEADORBEHINDAHEAD = 261,
     AHEADORBEHINDBEHIND = 262,
     AHEADORBEHINDEXACT = 263,
     ALONGPATH = 264,
     ANDEXPRESSION = 265,
     ANGLETAPER = 266,
     APLIFTPATHANGLE = 267,
     APLIFTPATHTANGENT = 268,
     APPROVAL = 269,
     APPROVALSTATUS = 270,
     APRETRACTANGLE = 271,
     APRETRACTTANGENT = 272,
     ASSIGNMENT = 273,
     AXIS1PLACEMENT = 274,
     AXIS2PLACEMENT3D = 275,
     AXISTRAJECTORY = 276,
     BACKBORING = 277,
     BACKSIDECOUNTERBORE = 278,
     BACKSIDECOUNTERSINK = 279,
     BALLENDMILL = 280,
     BEZIERCURVE = 281,
     BEZIERSURFACE = 282,
     BIDIRECTIONALCONTOUR = 283,
     BIDIRECTIONALMILLING = 284,
     BLOCK = 285,
     BORING = 286,
     BORINGTOOL = 287,
     BOSS = 288,
     BOTTOMANDSIDEFINISHMILLING = 289,
     BOTTOMANDSIDEROUGHMILLING = 290,
     BOTTOMORSIDEBOTTOM = 291,
     BOTTOMORSIDEBOTTOMANDSIDE = 292,
     BOTTOMORSIDESIDE = 293,
     BOUNDEDPCURVE = 294,
     BSPLINECURVEFORMCIRCULARARC = 295,
     BSPLINECURVEFORMELLIPTICARC = 296,
     BSPLINECURVEFORMHYPERBOLICARC = 297,
     BSPLINECURVEFORMPARABOLICARC = 298,
     BSPLINECURVEFORMPOLYLINEFORM = 299,
     BSPLINECURVEFORMUNSPECIFIED = 300,
     BSPLINECURVEWITHKNOTS = 301,
     BSPLINESURFACEFORMCONICALSURF = 302,
     BSPLINESURFACEFORMCYLINDRICALSURF = 303,
     BSPLINESURFACEFORMGENERALIZEDCONE = 304,
     BSPLINESURFACEFORMPLANESURF = 305,
     BSPLINESURFACEFORMQUADRICSURF = 306,
     BSPLINESURFACEFORMRULEDSURF = 307,
     BSPLINESURFACEFORMSPHERICALSURF = 308,
     BSPLINESURFACEFORMSURFOFLINEAREXTRUSION = 309,
     BSPLINESURFACEFORMSURFOFREVOLUTION = 310,
     BSPLINESURFACEFORMTOROIDALSURF = 311,
     BSPLINESURFACEFORMUNSPECIFIED = 312,
     BSPLINESURFACEWITHKNOTS = 313,
     BULLNOSEENDMILL = 314,
     C = 315,
     CALENDARDATE = 316,
     CARTESIANPOINT = 317,
     CATALOGUETHREAD = 318,
     CENTERDRILL = 319,
     CENTERDRILLING = 320,
     CENTERMILLING = 321,
     CHAMFER = 322,
     CHANNEL = 323,
     CIRCLE = 324,
     CIRCULARCLOSEDPROFILE = 325,
     CIRCULARCLOSEDSHAPEPROFILE = 326,
     CIRCULAROFFSET = 327,
     CIRCULAROMIT = 328,
     CIRCULARPATTERN = 329,
     CLOSEDPOCKET = 330,
     CLOSEDSHELL = 331,
     COMBINEDDRILLANDREAMER = 332,
     COMBINEDDRILLANDTAP = 333,
     COMPARISONEQUAL = 334,
     COMPARISONGREATER = 335,
     COMPARISONGREATEREQUAL = 336,
     COMPARISONLESS = 337,
     COMPARISONLESSEQUAL = 338,
     COMPARISONNOTEQUAL = 339,
     COMPLETECIRCULARPATH = 340,
     COMPOSITECURVE = 341,
     COMPOSITECURVESEGMENT = 342,
     CONICALHOLEBOTTOM = 343,
     CONNECTDIRECT = 344,
     CONNECTSECPLANE = 345,
     CONTACTTYPEFRONT = 346,
     CONTACTTYPESIDE = 347,
     CONTOURBIDIRECTIONAL = 348,
     CONTOURPARALLEL = 349,
     CONTOURSPIRAL = 350,
     COORDINATEDUNIVERSALTIMEOFFSET = 351,
     COUNTERBORE = 352,
     COUNTERBOREHOLE = 353,
     COUNTERSINK = 354,
     COUNTERSINKING = 355,
     COUNTERSUNKHOLE = 356,
     CURVEWITHNORMALVECTOR = 357,
     CUTMODETYPECLIMB = 358,
     CUTMODETYPECONVENTIONAL = 359,
     CUTTERCONTACTTRAJECTORY = 360,
     CUTTERLOCATIONTRAJECTORY = 361,
     CUTTINGCOMPONENT = 362,
     CUTTINGEDGETECHNOLOGICALDATA = 363,
     DATA = 364,
     DATEANDTIME = 365,
     DEFINEDTHREAD = 366,
     DEFINITIONALREPRESENTATION = 367,
     DESCRIPTIVEPARAMETER = 368,
     DIAMETERTAPER = 369,
     DIRECTION = 370,
     DISPLAYMESSAGE = 371,
     DOVETAILMILL = 372,
     DRILLING = 373,
     DRILLINGTYPESTRATEGY = 374,
     EDGECURVE = 375,
     EDGELOOP = 376,
     EDGEROUND = 377,
     ELLIPSE = 378,
     ENDSEC = 379,
     EXCHANGEPALLET = 380,
     EXPLICITSTRATEGY = 381,
     FACEBOUND = 382,
     FACEMILL = 383,
     FACEOUTERBOUND = 384,
     FALSE = 385,
     FEEDSTOP = 386,
     FILEDESCRIPTION = 387,
     FILEEND = 388,
     FILENAME = 389,
     FILESCHEMA = 390,
     FILESTART = 391,
     FITTINGTYPEHOLE = 392,
     FITTINGTYPESHAFT = 393,
     FIVEAXESCONSTTILTYAW = 394,
     FIVEAXESVARTILTYAW = 395,
     FLATHOLEBOTTOM = 396,
     FLATSLOTENDTYPE = 397,
     FLATWITHRADIUSHOLEBOTTOM = 398,
     FREEFORMOPERATION = 399,
     GENERALCLOSEDPROFILE = 400,
     GENERALOUTSIDEPROFILE = 401,
     GENERALPATH = 402,
     GENERALPATTERN = 403,
     GENERALPOCKETBOTTOMCONDITION = 404,
     GENERALPROFILE = 405,
     GENERALPROFILEFLOOR = 406,
     GENERALSHAPEPROFILE = 407,
     HEADER = 408,
     HELIX = 409,
     HYPERBOLA = 410,
     IFSTATEMENT = 411,
     INDEXPALLET = 412,
     INDEXTABLE = 413,
     INPROCESSGEOMETRY = 414,
     KNOTTYPEPIECEWISEBEZIERKNOTS = 415,
     KNOTTYPEQUASIUNIFORMKNOTS = 416,
     KNOTTYPEUNIFORMKNOTS = 417,
     KNOTTYPEUNSPECIFIED = 418,
     LEADINGLINESTRATEGY = 419,
     LEFT = 420,
     LIMITSANDFITS = 421,
     LINE = 422,
     LINEARPATH = 423,
     LINEARPROFILE = 424,
     LOADTOOL = 425,
     LOCALTIME = 426,
     LOOPSLOTENDTYPE = 427,
     MACHINEDSURFACE = 428,
     MACHININGWORKINGSTEP = 429,
     MANIFOLDSOLIDBREP = 430,
     MATERIAL = 431,
     MILLINGCUTTINGTOOL = 432,
     MILLINGMACHINEFUNCTIONS = 433,
     MILLINGTECHNOLOGY = 434,
     MILLINGTHREADINGTOOL = 435,
     MILLINGTOOLDIMENSION = 436,
     MULTISTEPDRILLING = 437,
     NCCONSTANT = 438,
     NCVARIABLE = 439,
     NEUTRAL = 440,
     NGONCLOSEDPROFILE = 441,
     NONSEQUENTIAL = 442,
     NOTEXPRESSION = 443,
     NUMERICPARAMETER = 444,
     OFFSETVECTOR = 445,
     OPENPOCKET = 446,
     OPENSHELL = 447,
     OPENSLOTENDTYPE = 448,
     OPTIONALSTOP = 449,
     ORDINALDATE = 450,
     OREXPRESSION = 451,
     ORIENTEDEDGE = 452,
     PARABOLA = 453,
     PARALLEL = 454,
     PARTIALAREADEFINITION = 455,
     PARTIALCIRCULARPATH = 456,
     PARTIALCIRCULARPROFILE = 457,
     PARTIALCIRCULARSHAPEPROFILE = 458,
     PATHMODETYPEFORWARD = 459,
     PATHMODETYPEZIGZAG = 460,
     PCURVE = 461,
     PERSON = 462,
     PERSONANDADDRESS = 463,
     PLANARFACE = 464,
     PLANARPOCKETBOTTOMCONDITION = 465,
     PLANARPROFILEFLOOR = 466,
     PLANE = 467,
     PLANECCSTRATEGY = 468,
     PLANECLSTRATEGY = 469,
     PLANEFINISHMILLING = 470,
     PLANEROUGHMILLING = 471,
     PLUNGEHELIX = 472,
     PLUNGERAMP = 473,
     PLUNGETOOLAXIS = 474,
     PLUNGEZIGZAG = 475,
     PLUSMINUSVALUE = 476,
     POLYLINE = 477,
     PROCESSMODEL = 478,
     PROCESSMODELLIST = 479,
     PROGRAMSTOP = 480,
     PROJECT = 481,
     QUASIUNIFORMCURVE = 482,
     QUASIUNIFORMSURFACE = 483,
     RADIUSEDPOCKETBOTTOMCONDITION = 484,
     RADIUSEDSLOTENDTYPE = 485,
     RAPIDMOVEMENT = 486,
     RATIONALBSPLINECURVE = 487,
     RATIONALBSPLINESURFACE = 488,
     REAMING = 489,
     RECTANGULARCLOSEDPROFILE = 490,
     RECTANGULARCLOSEDSHAPEPROFILE = 491,
     RECTANGULAROFFSET = 492,
     RECTANGULAROMIT = 493,
     RECTANGULAROPENSHAPEPROFILE = 494,
     RECTANGULARPATTERN = 495,
     REGIONPROJECTION = 496,
     REGIONSURFACELIST = 497,
     REPRESENTATION = 498,
     REPRESENTATIONCONTEXT = 499,
     RIGHT = 500,
     RIGHTCIRCULARCYLINDER = 501,
     ROTDIRECTIONCCW = 502,
     ROTDIRECTIONCW = 503,
     ROUNDEDEND = 504,
     ROUNDEDUPROFILE = 505,
     ROUNDHOLE = 506,
     SELECTIVE = 507,
     SETMARK = 508,
     SETUP = 509,
     SETUPINSTRUCTION = 510,
     SHAPEREPRESENTATION = 511,
     SIDEFINISHMILLING = 512,
     SIDEMILL = 513,
     SIDEROUGHMILLING = 514,
     SLOT = 515,
     SPADEDRILL = 516,
     SPECIFICATION = 517,
     SPECIFICATIONUSAGECONSTRAINT = 518,
     SPEEDNAMERAPID = 519,
     SPHERICALCAP = 520,
     SPHERICALHOLEBOTTOM = 521,
     SPHERICALSURFACE = 522,
     SQUAREUPROFILE = 523,
     STEP = 524,
     STROKECONNECTIONSTRATEGYDEGOUGE = 525,
     STROKECONNECTIONSTRATEGYLIFTSHIFTPLUNGE = 526,
     STROKECONNECTIONSTRATEGYLOOPBACK = 527,
     STROKECONNECTIONSTRATEGYSTRAIGHTLINE = 528,
     SURFACEOFLINEAREXTRUSION = 529,
     SURFACEOFREVOLUTION = 530,
     SURFACETEXTUREPARAMETER = 531,
     TAP = 532,
     TAPEREDDRILL = 533,
     TAPEREDENDMILL = 534,
     TAPEREDREAMER = 535,
     TAPEREDTAP = 536,
     TAPPING = 537,
     TEEPROFILE = 538,
     THREADDRILLING = 539,
     THREADMILL = 540,
     THREEAXES = 541,
     THREEAXESTILTEDTOOL = 542,
     THROUGHBOTTOMCONDITION = 543,
     THROUGHPOCKETBOTTOMCONDITION = 544,
     THROUGHPROFILEFLOOR = 545,
     TOLERANCEDLENGTHMEASURE = 546,
     TOLERANCES = 547,
     TOOLLENGTHPROBING = 548,
     TOOLPATHFEATURE = 549,
     TOOLPATHLIST = 550,
     TOOLPATHSPEED = 551,
     TOOLPATHTYPEAPPROACH = 552,
     TOOLPATHTYPECONNECT = 553,
     TOOLPATHTYPECONTACT = 554,
     TOOLPATHTYPELIFT = 555,
     TOOLPATHTYPENONCONTACT = 556,
     TOOLPATHTYPETRAJECTORYPATH = 557,
     TOOLRADIUSPROBING = 558,
     TOOLREFERENCEPOINTCCP = 559,
     TOOLREFERENCEPOINTTCP = 560,
     TOPOLOGICALREGION = 561,
     TOUCHPROBE = 562,
     TRANSITIONCODECONTINUOUS = 563,
     TRANSITIONCODECONTSAMEGRADIENT = 564,
     TRANSITIONCODECONTSAMEGRADIENTSAMECURVATURE = 565,
     TRANSITIONCODEDISCONTINUOUS = 566,
     TRIMMEDCURVE = 567,
     TRIMMINGPREFERENCECARTESIAN = 568,
     TRIMMINGPREFERENCEPARAMETER = 569,
     TRIMMINGPREFERENCEUNSPECIFIED = 570,
     TRUE = 571,
     TSLOTMILL = 572,
     TWISTDRILL = 573,
     TWOAXES = 574,
     UNIDIRECTIONALMILLING = 575,
     UNIFORMCURVE = 576,
     UNIFORMSURFACE = 577,
     UNKNOWN = 578,
     UNLOADTOOL = 579,
     USERDEFINEDTOOL = 580,
     UVSTRATEGY = 581,
     VECTOR = 582,
     VEEPROFILE = 583,
     VERTEXLOOP = 584,
     VERTEXPOINT = 585,
     WAITFORMARK = 586,
     WEEKOFYEARANDDAYDATE = 587,
     WHILESTATEMENT = 588,
     WOODRUFFKEYSEATMILL = 589,
     WOODRUFFSLOTENDTYPE = 590,
     WORKPIECE = 591,
     WORKPIECECOMPLETEPROBING = 592,
     WORKPIECEPROBING = 593,
     WORKPIECESETUP = 594,
     WORKPLAN = 595,
     XOREXPRESSION = 596,
     CHARSTRING = 597,
     INTSTRING = 598,
     REALSTRING = 599,
     BAD = 600,
     COLON = 601,
     DOLLAR = 602,
     EQUALS = 603,
     LBOX = 604,
     LPAREN = 605,
     RBOX = 606,
     RPAREN = 607,
     SEMICOLON = 608,
     SHARP = 609,
     SLASH = 610
   };
#endif
/* Tokens.  */
#define ADDRESS 258
#define ADVANCEDBREPSHAPEREPRESENTATION 259
#define ADVANCEDFACE 260
#define AHEADORBEHINDAHEAD 261
#define AHEADORBEHINDBEHIND 262
#define AHEADORBEHINDEXACT 263
#define ALONGPATH 264
#define ANDEXPRESSION 265
#define ANGLETAPER 266
#define APLIFTPATHANGLE 267
#define APLIFTPATHTANGENT 268
#define APPROVAL 269
#define APPROVALSTATUS 270
#define APRETRACTANGLE 271
#define APRETRACTTANGENT 272
#define ASSIGNMENT 273
#define AXIS1PLACEMENT 274
#define AXIS2PLACEMENT3D 275
#define AXISTRAJECTORY 276
#define BACKBORING 277
#define BACKSIDECOUNTERBORE 278
#define BACKSIDECOUNTERSINK 279
#define BALLENDMILL 280
#define BEZIERCURVE 281
#define BEZIERSURFACE 282
#define BIDIRECTIONALCONTOUR 283
#define BIDIRECTIONALMILLING 284
#define BLOCK 285
#define BORING 286
#define BORINGTOOL 287
#define BOSS 288
#define BOTTOMANDSIDEFINISHMILLING 289
#define BOTTOMANDSIDEROUGHMILLING 290
#define BOTTOMORSIDEBOTTOM 291
#define BOTTOMORSIDEBOTTOMANDSIDE 292
#define BOTTOMORSIDESIDE 293
#define BOUNDEDPCURVE 294
#define BSPLINECURVEFORMCIRCULARARC 295
#define BSPLINECURVEFORMELLIPTICARC 296
#define BSPLINECURVEFORMHYPERBOLICARC 297
#define BSPLINECURVEFORMPARABOLICARC 298
#define BSPLINECURVEFORMPOLYLINEFORM 299
#define BSPLINECURVEFORMUNSPECIFIED 300
#define BSPLINECURVEWITHKNOTS 301
#define BSPLINESURFACEFORMCONICALSURF 302
#define BSPLINESURFACEFORMCYLINDRICALSURF 303
#define BSPLINESURFACEFORMGENERALIZEDCONE 304
#define BSPLINESURFACEFORMPLANESURF 305
#define BSPLINESURFACEFORMQUADRICSURF 306
#define BSPLINESURFACEFORMRULEDSURF 307
#define BSPLINESURFACEFORMSPHERICALSURF 308
#define BSPLINESURFACEFORMSURFOFLINEAREXTRUSION 309
#define BSPLINESURFACEFORMSURFOFREVOLUTION 310
#define BSPLINESURFACEFORMTOROIDALSURF 311
#define BSPLINESURFACEFORMUNSPECIFIED 312
#define BSPLINESURFACEWITHKNOTS 313
#define BULLNOSEENDMILL 314
#define C 315
#define CALENDARDATE 316
#define CARTESIANPOINT 317
#define CATALOGUETHREAD 318
#define CENTERDRILL 319
#define CENTERDRILLING 320
#define CENTERMILLING 321
#define CHAMFER 322
#define CHANNEL 323
#define CIRCLE 324
#define CIRCULARCLOSEDPROFILE 325
#define CIRCULARCLOSEDSHAPEPROFILE 326
#define CIRCULAROFFSET 327
#define CIRCULAROMIT 328
#define CIRCULARPATTERN 329
#define CLOSEDPOCKET 330
#define CLOSEDSHELL 331
#define COMBINEDDRILLANDREAMER 332
#define COMBINEDDRILLANDTAP 333
#define COMPARISONEQUAL 334
#define COMPARISONGREATER 335
#define COMPARISONGREATEREQUAL 336
#define COMPARISONLESS 337
#define COMPARISONLESSEQUAL 338
#define COMPARISONNOTEQUAL 339
#define COMPLETECIRCULARPATH 340
#define COMPOSITECURVE 341
#define COMPOSITECURVESEGMENT 342
#define CONICALHOLEBOTTOM 343
#define CONNECTDIRECT 344
#define CONNECTSECPLANE 345
#define CONTACTTYPEFRONT 346
#define CONTACTTYPESIDE 347
#define CONTOURBIDIRECTIONAL 348
#define CONTOURPARALLEL 349
#define CONTOURSPIRAL 350
#define COORDINATEDUNIVERSALTIMEOFFSET 351
#define COUNTERBORE 352
#define COUNTERBOREHOLE 353
#define COUNTERSINK 354
#define COUNTERSINKING 355
#define COUNTERSUNKHOLE 356
#define CURVEWITHNORMALVECTOR 357
#define CUTMODETYPECLIMB 358
#define CUTMODETYPECONVENTIONAL 359
#define CUTTERCONTACTTRAJECTORY 360
#define CUTTERLOCATIONTRAJECTORY 361
#define CUTTINGCOMPONENT 362
#define CUTTINGEDGETECHNOLOGICALDATA 363
#define DATA 364
#define DATEANDTIME 365
#define DEFINEDTHREAD 366
#define DEFINITIONALREPRESENTATION 367
#define DESCRIPTIVEPARAMETER 368
#define DIAMETERTAPER 369
#define DIRECTION 370
#define DISPLAYMESSAGE 371
#define DOVETAILMILL 372
#define DRILLING 373
#define DRILLINGTYPESTRATEGY 374
#define EDGECURVE 375
#define EDGELOOP 376
#define EDGEROUND 377
#define ELLIPSE 378
#define ENDSEC 379
#define EXCHANGEPALLET 380
#define EXPLICITSTRATEGY 381
#define FACEBOUND 382
#define FACEMILL 383
#define FACEOUTERBOUND 384
#define FALSE 385
#define FEEDSTOP 386
#define FILEDESCRIPTION 387
#define FILEEND 388
#define FILENAME 389
#define FILESCHEMA 390
#define FILESTART 391
#define FITTINGTYPEHOLE 392
#define FITTINGTYPESHAFT 393
#define FIVEAXESCONSTTILTYAW 394
#define FIVEAXESVARTILTYAW 395
#define FLATHOLEBOTTOM 396
#define FLATSLOTENDTYPE 397
#define FLATWITHRADIUSHOLEBOTTOM 398
#define FREEFORMOPERATION 399
#define GENERALCLOSEDPROFILE 400
#define GENERALOUTSIDEPROFILE 401
#define GENERALPATH 402
#define GENERALPATTERN 403
#define GENERALPOCKETBOTTOMCONDITION 404
#define GENERALPROFILE 405
#define GENERALPROFILEFLOOR 406
#define GENERALSHAPEPROFILE 407
#define HEADER 408
#define HELIX 409
#define HYPERBOLA 410
#define IFSTATEMENT 411
#define INDEXPALLET 412
#define INDEXTABLE 413
#define INPROCESSGEOMETRY 414
#define KNOTTYPEPIECEWISEBEZIERKNOTS 415
#define KNOTTYPEQUASIUNIFORMKNOTS 416
#define KNOTTYPEUNIFORMKNOTS 417
#define KNOTTYPEUNSPECIFIED 418
#define LEADINGLINESTRATEGY 419
#define LEFT 420
#define LIMITSANDFITS 421
#define LINE 422
#define LINEARPATH 423
#define LINEARPROFILE 424
#define LOADTOOL 425
#define LOCALTIME 426
#define LOOPSLOTENDTYPE 427
#define MACHINEDSURFACE 428
#define MACHININGWORKINGSTEP 429
#define MANIFOLDSOLIDBREP 430
#define MATERIAL 431
#define MILLINGCUTTINGTOOL 432
#define MILLINGMACHINEFUNCTIONS 433
#define MILLINGTECHNOLOGY 434
#define MILLINGTHREADINGTOOL 435
#define MILLINGTOOLDIMENSION 436
#define MULTISTEPDRILLING 437
#define NCCONSTANT 438
#define NCVARIABLE 439
#define NEUTRAL 440
#define NGONCLOSEDPROFILE 441
#define NONSEQUENTIAL 442
#define NOTEXPRESSION 443
#define NUMERICPARAMETER 444
#define OFFSETVECTOR 445
#define OPENPOCKET 446
#define OPENSHELL 447
#define OPENSLOTENDTYPE 448
#define OPTIONALSTOP 449
#define ORDINALDATE 450
#define OREXPRESSION 451
#define ORIENTEDEDGE 452
#define PARABOLA 453
#define PARALLEL 454
#define PARTIALAREADEFINITION 455
#define PARTIALCIRCULARPATH 456
#define PARTIALCIRCULARPROFILE 457
#define PARTIALCIRCULARSHAPEPROFILE 458
#define PATHMODETYPEFORWARD 459
#define PATHMODETYPEZIGZAG 460
#define PCURVE 461
#define PERSON 462
#define PERSONANDADDRESS 463
#define PLANARFACE 464
#define PLANARPOCKETBOTTOMCONDITION 465
#define PLANARPROFILEFLOOR 466
#define PLANE 467
#define PLANECCSTRATEGY 468
#define PLANECLSTRATEGY 469
#define PLANEFINISHMILLING 470
#define PLANEROUGHMILLING 471
#define PLUNGEHELIX 472
#define PLUNGERAMP 473
#define PLUNGETOOLAXIS 474
#define PLUNGEZIGZAG 475
#define PLUSMINUSVALUE 476
#define POLYLINE 477
#define PROCESSMODEL 478
#define PROCESSMODELLIST 479
#define PROGRAMSTOP 480
#define PROJECT 481
#define QUASIUNIFORMCURVE 482
#define QUASIUNIFORMSURFACE 483
#define RADIUSEDPOCKETBOTTOMCONDITION 484
#define RADIUSEDSLOTENDTYPE 485
#define RAPIDMOVEMENT 486
#define RATIONALBSPLINECURVE 487
#define RATIONALBSPLINESURFACE 488
#define REAMING 489
#define RECTANGULARCLOSEDPROFILE 490
#define RECTANGULARCLOSEDSHAPEPROFILE 491
#define RECTANGULAROFFSET 492
#define RECTANGULAROMIT 493
#define RECTANGULAROPENSHAPEPROFILE 494
#define RECTANGULARPATTERN 495
#define REGIONPROJECTION 496
#define REGIONSURFACELIST 497
#define REPRESENTATION 498
#define REPRESENTATIONCONTEXT 499
#define RIGHT 500
#define RIGHTCIRCULARCYLINDER 501
#define ROTDIRECTIONCCW 502
#define ROTDIRECTIONCW 503
#define ROUNDEDEND 504
#define ROUNDEDUPROFILE 505
#define ROUNDHOLE 506
#define SELECTIVE 507
#define SETMARK 508
#define SETUP 509
#define SETUPINSTRUCTION 510
#define SHAPEREPRESENTATION 511
#define SIDEFINISHMILLING 512
#define SIDEMILL 513
#define SIDEROUGHMILLING 514
#define SLOT 515
#define SPADEDRILL 516
#define SPECIFICATION 517
#define SPECIFICATIONUSAGECONSTRAINT 518
#define SPEEDNAMERAPID 519
#define SPHERICALCAP 520
#define SPHERICALHOLEBOTTOM 521
#define SPHERICALSURFACE 522
#define SQUAREUPROFILE 523
#define STEP 524
#define STROKECONNECTIONSTRATEGYDEGOUGE 525
#define STROKECONNECTIONSTRATEGYLIFTSHIFTPLUNGE 526
#define STROKECONNECTIONSTRATEGYLOOPBACK 527
#define STROKECONNECTIONSTRATEGYSTRAIGHTLINE 528
#define SURFACEOFLINEAREXTRUSION 529
#define SURFACEOFREVOLUTION 530
#define SURFACETEXTUREPARAMETER 531
#define TAP 532
#define TAPEREDDRILL 533
#define TAPEREDENDMILL 534
#define TAPEREDREAMER 535
#define TAPEREDTAP 536
#define TAPPING 537
#define TEEPROFILE 538
#define THREADDRILLING 539
#define THREADMILL 540
#define THREEAXES 541
#define THREEAXESTILTEDTOOL 542
#define THROUGHBOTTOMCONDITION 543
#define THROUGHPOCKETBOTTOMCONDITION 544
#define THROUGHPROFILEFLOOR 545
#define TOLERANCEDLENGTHMEASURE 546
#define TOLERANCES 547
#define TOOLLENGTHPROBING 548
#define TOOLPATHFEATURE 549
#define TOOLPATHLIST 550
#define TOOLPATHSPEED 551
#define TOOLPATHTYPEAPPROACH 552
#define TOOLPATHTYPECONNECT 553
#define TOOLPATHTYPECONTACT 554
#define TOOLPATHTYPELIFT 555
#define TOOLPATHTYPENONCONTACT 556
#define TOOLPATHTYPETRAJECTORYPATH 557
#define TOOLRADIUSPROBING 558
#define TOOLREFERENCEPOINTCCP 559
#define TOOLREFERENCEPOINTTCP 560
#define TOPOLOGICALREGION 561
#define TOUCHPROBE 562
#define TRANSITIONCODECONTINUOUS 563
#define TRANSITIONCODECONTSAMEGRADIENT 564
#define TRANSITIONCODECONTSAMEGRADIENTSAMECURVATURE 565
#define TRANSITIONCODEDISCONTINUOUS 566
#define TRIMMEDCURVE 567
#define TRIMMINGPREFERENCECARTESIAN 568
#define TRIMMINGPREFERENCEPARAMETER 569
#define TRIMMINGPREFERENCEUNSPECIFIED 570
#define TRUE 571
#define TSLOTMILL 572
#define TWISTDRILL 573
#define TWOAXES 574
#define UNIDIRECTIONALMILLING 575
#define UNIFORMCURVE 576
#define UNIFORMSURFACE 577
#define UNKNOWN 578
#define UNLOADTOOL 579
#define USERDEFINEDTOOL 580
#define UVSTRATEGY 581
#define VECTOR 582
#define VEEPROFILE 583
#define VERTEXLOOP 584
#define VERTEXPOINT 585
#define WAITFORMARK 586
#define WEEKOFYEARANDDAYDATE 587
#define WHILESTATEMENT 588
#define WOODRUFFKEYSEATMILL 589
#define WOODRUFFSLOTENDTYPE 590
#define WORKPIECE 591
#define WORKPIECECOMPLETEPROBING 592
#define WORKPIECEPROBING 593
#define WORKPIECESETUP 594
#define WORKPLAN 595
#define XOREXPRESSION 596
#define CHARSTRING 597
#define INTSTRING 598
#define REALSTRING 599
#define BAD 600
#define COLON 601
#define DOLLAR 602
#define EQUALS 603
#define LBOX 604
#define LPAREN 605
#define RBOX 606
#define RPAREN 607
#define SEMICOLON 608
#define SHARP 609
#define SLASH 610




#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE

{
  inputFile                        * val1;
  instance                         * val2;
  address                          * val3;
  advancedBrepShapeRepresentation  * val4;
  advancedFace                     * val5;
  aheadOrBehind                    * val6;
  aheadOrBehindAhead               * val7;
  aheadOrBehindBehind              * val8;
  aheadOrBehindExact               * val9;
  alongPath                        * val10;
  andExpression                    * val11;
  angleTaper                       * val12;
  apLiftPathAngle                  * val13;
  apLiftPathTangent                * val14;
  approval                         * val15;
  approvalStatus                   * val16;
  apRetractAngle                   * val17;
  apRetractTangent                 * val18;
  assignment                       * val19;
  aString                          * val20;
  axis1placement                   * val21;
  axis2placement3d                 * val22;
  std::list<axis2placement3d *>    * val23;
  axisTrajectory                   * val24;
  backBoring                       * val25;
  backsideCounterbore              * val26;
  backsideCountersink              * val27;
  ballEndmill                      * val28;
  bezierCurve                      * val29;
  bezierSurface                    * val30;
  bidirectionalContour             * val31;
  bidirectionalMilling             * val32;
  block                            * val33;
  boolean                          * val34;
  std::list<booleanExpression *>   * val35;
  booleanFalse                     * val36;
  booleanTrue                      * val37;
  boring                           * val38;
  boringTool                       * val39;
  boss                             * val40;
  std::list<boss *>                * val41;
  bottomAndSideFinishMilling       * val42;
  bottomAndSideRoughMilling        * val43;
  bottomOrSide                     * val44;
  bottomOrSideBottom               * val45;
  bottomOrSideSide                 * val46;
  bottomOrSideBottomAndSide        * val47;
  std::list<boundedCurve *>        * val48;
  boundedPCurve                    * val49;
  std::list<boundedSurface *>      * val50;
  bSplineCurveForm                 * val51;
  bSplineCurveFormPolylineForm     * val52;
  bSplineCurveFormCircularArc      * val53;
  bSplineCurveFormEllipticArc      * val54;
  bSplineCurveFormParabolicArc     * val55;
  bSplineCurveFormHyperbolicArc    * val56;
  bSplineCurveFormUnspecified      * val57;
  bSplineCurveWithKnots            * val58;
  bSplineSurfaceForm               * val59;
  bSplineSurfaceFormConicalSurf    * val60;
  bSplineSurfaceFormCylindricalSurf * val61;
  bSplineSurfaceFormGeneralizedCone * val62;
  bSplineSurfaceFormPlaneSurf      * val63;
  bSplineSurfaceFormQuadricSurf    * val64;
  bSplineSurfaceFormRuledSurf      * val65;
  bSplineSurfaceFormSphericalSurf  * val66;
  bSplineSurfaceFormSurfOfLinearExtrusion * val67;
  bSplineSurfaceFormSurfOfRevolution * val68;
  bSplineSurfaceFormToroidalSurf   * val69;
  bSplineSurfaceFormUnspecified    * val70;
  bSplineSurfaceWithKnots          * val71;
  bullnoseEndmill                  * val72;
  calendarDate                     * val73;
  cartesianPoint                   * val74;
  std::list<cartesianPoint *>      * val75;
  catalogueThread                  * val76;
  centerDrill                      * val77;
  centerDrilling                   * val78;
  centerMilling                    * val79;
  chamfer                          * val80;
  channel                          * val81;
  circle                           * val82;
  circularClosedProfile            * val83;
  circularClosedShapeProfile       * val84;
  circularOffset                   * val85;
  std::list<circularOffset *>      * val86;
  circularOmit                     * val87;
  std::list<circularOmit *>        * val88;
  circularPattern                  * val89;
  closedPocket                     * val90;
  closedShell                      * val91;
  combinedDrillAndReamer           * val92;
  combinedDrillAndTap              * val93;
  comparisonEqual                  * val94;
  comparisonGreater                * val95;
  comparisonGreaterEqual           * val96;
  comparisonLess                   * val97;
  comparisonLessEqual              * val98;
  comparisonNotEqual               * val99;
  completeCircularPath             * val100;
  compositeCurve                   * val101;
  compositeCurveSegment            * val102;
  std::list<compositeCurveSegment *> * val103;
  std::list<compoundFeatureSelect *> * val104;
  conicalHoleBottom                * val105;
  connectDirect                    * val106;
  connectSecplane                  * val107;
  contactType                      * val108;
  contactTypeSide                  * val109;
  contactTypeFront                 * val110;
  contourBidirectional             * val111;
  contourParallel                  * val112;
  contourSpiral                    * val113;
  coordinatedUniversalTimeOffset   * val114;
  counterbore                      * val115;
  counterboreHole                  * val116;
  countersink                      * val117;
  counterSinking                   * val118;
  countersunkHole                  * val119;
  curveWithNormalVector            * val120;
  cutmodeType                      * val121;
  cutmodeTypeClimb                 * val122;
  cutmodeTypeConventional          * val123;
  cutterContactTrajectory          * val124;
  cutterLocationTrajectory         * val125;
  cuttingComponent                 * val126;
  std::list<cuttingComponent *>    * val127;
  cuttingEdgeTechnologicalData     * val128;
  dataSection                      * val129;
  dataStarter                      * val130;
  dateAndTime                      * val131;
  definedThread                    * val132;
  definitionalRepresentation       * val133;
  descriptiveParameter             * val134;
  diameterTaper                    * val135;
  direction                        * val136;
  displayMessage                   * val137;
  dovetailMill                     * val138;
  drilling                         * val139;
  drillingTypeStrategy             * val140;
  edgeCurve                        * val141;
  edgeLoop                         * val142;
  edgeRound                        * val143;
  ellipse                          * val144;
  endSection                       * val145;
  exchangePallet                   * val146;
  std::list<executable *>          * val147;
  explicitStrategy                 * val148;
  std::list<face *>                * val149;
  facemill                         * val150;
  faceBound                        * val151;
  std::list<faceBound *>           * val152;
  faceOuterBound                   * val153;
  feedstop                         * val154;
  fileDescription                  * val155;
  fileEnd                          * val156;
  fileName                         * val157;
  fileSchema                       * val158;
  fileStart                        * val159;
  fittingType                      * val160;
  fittingTypeHole                  * val161;
  fittingTypeShaft                 * val162;
  fiveAxesVarTiltYaw               * val163;
  fiveAxesConstTiltYaw             * val164;
  flatHoleBottom                   * val165;
  flatSlotEndType                  * val166;
  flatWithRadiusHoleBottom         * val167;
  freeformOperation                * val168;
  generalClosedProfile             * val169;
  generalOutsideProfile            * val170;
  generalPath                      * val171;
  generalPattern                   * val172;
  generalPocketBottomCondition     * val173;
  generalProfile                   * val174;
  generalProfileFloor              * val175;
  generalShapeProfile              * val176;
  hand                             * val177;
  handLeft                         * val178;
  handNeutral                      * val179;
  handRight                        * val180;
  headerSection                    * val181;
  headerStarter                    * val182;
  helix                            * val183;
  hyperbola                        * val184;
  ifStatement                      * val185;
  indexPallet                      * val186;
  indexTable                       * val187;
  inProcessGeometry                * val188;
  instanceId                       * val189;
  std::list<instance *>            * val190;
  integer                          * val191;
  std::list<integer *>             * val192;
  knotType                         * val193;
  knotTypePiecewiseBezierKnots     * val194;
  knotTypeQuasiUniformKnots        * val195;
  knotTypeUniformKnots             * val196;
  knotTypeUnspecified              * val197;
  leadingLineStrategy              * val198;
  leftOrRight                      * val199;
  leftOrRightLeft                  * val200;
  leftOrRightRight                 * val201;
  limitsAndFits                    * val202;
  line                             * val203;
  linearPath                       * val204;
  linearProfile                    * val205;
  loadTool                         * val206;
  localTime                        * val207;
  logical                          * val208;
  logicalFalse                     * val209;
  logicalTrue                      * val210;
  logicalUnknown                   * val211;
  loopSlotEndType                  * val212;
  machinedSurface                  * val213;
  std::list<machinedSurface *>     * val214;
  std::list<machiningFeature *>    * val215;
  std::list<machiningOperation *>  * val216;
  machiningWorkingstep             * val217;
  manifoldSolidBrep                * val218;
  material                         * val219;
  millingCuttingTool               * val220;
  millingMachineFunctions          * val221;
  millingTechnology                * val222;
  millingThreadingTool             * val223;
  millingToolDimension             * val224;
  multistepDrilling                * val225;
  ncConstant                       * val226;
  ncVariable                       * val227;
  std::list<ncVariable *>          * val228;
  ngonClosedProfile                * val229;
  nonSequential                    * val230;
  notExpression                    * val231;
  numericParameter                 * val232;
  offsetVector                     * val233;
  openPocket                       * val234;
  openShell                        * val235;
  openSlotEndType                  * val236;
  optionalStop                     * val237;
  orExpression                     * val238;
  orientedEdge                     * val239;
  std::list<orientedEdge *>        * val240;
  ordinalDate                      * val241;
  parabola                         * val242;
  parallel                         * val243;
  parenAxis2placement3dListFull    * val244;
  parenBooleanExpressionListFull   * val245;
  parenBossList                    * val246;
  parenBoundedCurveListFull        * val247;
  parenBoundedSurfaceListFull      * val248;
  parenCartesianPointList          * val249;
  parenCartesianPointListFull      * val250;
  std::list<parenCartesianPointListFull *> * val251;
  parenCircularOffsetList          * val252;
  parenCircularOmitList            * val253;
  parenCompositeCurveSegmentListFull * val254;
  parenCompoundFeatureSelectListFull * val255;
  parenCuttingComponentListFull    * val256;
  parenExecutableList              * val257;
  parenExecutableListFull          * val258;
  parenFaceBoundListFull           * val259;
  parenFaceListFull                * val260;
  parenIntegerListFull             * val261;
  parenMachinedSurfaceListFull     * val262;
  parenMachiningFeatureListFull    * val263;
  parenMachiningOperationList      * val264;
  parenNcVariableListFull          * val265;
  parenOrientedEdgeListFull        * val266;
  parenParenCartesianPointListFullListFull * val267;
  parenParenRealListFullListFull   * val268;
  parenProcessModelLiszt           * val269;
  parenPropertyParameterList       * val270;
  parenRealListFull                * val271;
  std::list<parenRealListFull *>   * val272;
  parenRectangularOffsetList       * val273;
  parenRectangularOmitList         * val274;
  parenRepresentationItemListFull  * val275;
  parenSetupInstructionList        * val276;
  parenSlotEndTypeList             * val277;
  parenSpecificationUsageConstraintList * val278;
  parenStringList                  * val279;
  parenStringListFull              * val280;
  parenToolpathLisztFull           * val281;
  parenTrimmingSelectListFull      * val282;
  parenWorkpieceList               * val283;
  parenWorkpieceSetupList          * val284;
  partialAreaDefinition            * val285;
  partialCircularPath              * val286;
  partialCircularProfile           * val287;
  partialCircularShapeProfile      * val288;
  pathmodeType                     * val289;
  pathmodeTypeForward              * val290;
  pathmodeTypeZigzag               * val291;
  pcurve                           * val292;
  person                           * val293;
  personAndAddress                 * val294;
  planarFace                       * val295;
  planarPocketBottomCondition      * val296;
  planarProfileFloor               * val297;
  plane                            * val298;
  planeCcStrategy                  * val299;
  planeClStrategy                  * val300;
  planeFinishMilling               * val301;
  planeRoughMilling                * val302;
  plungeHelix                      * val303;
  plungeRamp                       * val304;
  plungeToolaxis                   * val305;
  plungeZigzag                     * val306;
  plusMinusValue                   * val307;
  polyline                         * val308;
  processModel                     * val309;
  processModelList                 * val310;
  std::list<processModel *>        * val311;
  programStop                      * val312;
  project                          * val313;
  std::list<propertyParameter *>   * val314;
  quasiUniformCurve                * val315;
  quasiUniformSurface              * val316;
  radiusedPocketBottomCondition    * val317;
  radiusedSlotEndType              * val318;
  rapidMovement                    * val319;
  rationalBSplineCurve             * val320;
  rationalBSplineSurface           * val321;
  real                             * val322;
  std::list<real *>                * val323;
  reaming                          * val324;
  rectangularClosedProfile         * val325;
  rectangularClosedShapeProfile    * val326;
  rectangularOffset                * val327;
  std::list<rectangularOffset *>   * val328;
  rectangularOmit                  * val329;
  std::list<rectangularOmit *>     * val330;
  rectangularOpenShapeProfile      * val331;
  rectangularPattern               * val332;
  regionProjection                 * val333;
  regionSurfaceList                * val334;
  representation                   * val335;
  representationContext            * val336;
  std::list<representationItem *>  * val337;
  rightCircularCylinder            * val338;
  rotDirection                     * val339;
  rotDirectionCw                   * val340;
  rotDirectionCcw                  * val341;
  roundedEnd                       * val342;
  roundedUProfile                  * val343;
  roundHole                        * val344;
  selective                        * val345;
  setMark                          * val346;
  setup                            * val347;
  setupInstruction                 * val348;
  std::list<setupInstruction *>    * val349;
  shapeRepresentation              * val350;
  sideMill                         * val351;
  sideFinishMilling                * val352;
  sideRoughMilling                 * val353;
  slot                             * val354;
  std::list<slotEndType *>         * val355;
  spadeDrill                       * val356;
  specification                    * val357;
  specificationUsageConstraint     * val358;
  std::list<specificationUsageConstraint *> * val359;
  speedName                        * val360;
  sphericalCap                     * val361;
  sphericalHoleBottom              * val362;
  sphericalSurface                 * val363;
  squareUProfile                   * val364;
  step                             * val365;
  std::list<char *>                * val366;
  strokeConnectionStrategy         * val367;
  strokeConnectionStrategyDegouge  * val368;
  strokeConnectionStrategyLiftShiftPlunge * val369;
  strokeConnectionStrategyLoopBack * val370;
  strokeConnectionStrategyStraightline * val371;
  surfaceOfLinearExtrusion         * val372;
  surfaceOfRevolution              * val373;
  surfaceTextureParameter          * val374;
  tap                              * val375;
  taperedTap                       * val376;
  taperedDrill                     * val377;
  taperedEndmill                   * val378;
  taperedReamer                    * val379;
  tapping                          * val380;
  teeProfile                       * val381;
  threadDrilling                   * val382;
  threadMill                       * val383;
  threeAxes                        * val384;
  threeAxesTiltedTool              * val385;
  throughBottomCondition           * val386;
  throughPocketBottomCondition     * val387;
  throughProfileFloor              * val388;
  tolerancedLengthMeasure          * val389;
  tolerances                       * val390;
  toolLengthProbing                * val391;
  toolpathFeature                  * val392;
  toolpathList                     * val393;
  std::list<toolpath *>            * val394;
  toolpathSpeed                    * val395;
  toolpathSpeedprofile             * val396;
  toolpathType                     * val397;
  toolpathTypeApproach             * val398;
  toolpathTypeConnect              * val399;
  toolpathTypeContact              * val400;
  toolpathTypeLift                 * val401;
  toolpathTypeNonContact           * val402;
  toolpathTypeTrajectoryPath       * val403;
  toolRadiusProbing                * val404;
  toolReferencePoint               * val405;
  toolReferencePointCcp            * val406;
  toolReferencePointTcp            * val407;
  topologicalRegion                * val408;
  touchProbe                       * val409;
  transitionCode                   * val410;
  transitionCodeContinuous         * val411;
  transitionCodeContSameGradient   * val412;
  transitionCodeContSameGradientSameCurvature * val413;
  transitionCodeDiscontinuous      * val414;
  trimmedCurve                     * val415;
  trimmingPreference               * val416;
  trimmingPreferenceCartesian      * val417;
  trimmingPreferenceParameter      * val418;
  trimmingPreferenceUnspecified    * val419;
  trimmingSelect                   * val420;
  std::list<trimmingSelect *>      * val421;
  tSlotMill                        * val422;
  twistDrill                       * val423;
  twoAxes                          * val424;
  unidirectionalMilling            * val425;
  uniformCurve                     * val426;
  uniformSurface                   * val427;
  unloadTool                       * val428;
  userDefinedTool                  * val429;
  uvStrategy                       * val430;
  vector                           * val431;
  veeProfile                       * val432;
  vertexLoop                       * val433;
  vertexPoint                      * val434;
  waitForMark                      * val435;
  weekOfYearAndDayDate             * val436;
  whileStatement                   * val437;
  woodruffKeyseatMill              * val438;
  woodruffSlotEndType              * val439;
  workpiece                        * val440;
  workpieceCompleteProbing         * val441;
  std::list<workpiece *>           * val442;
  workpieceProbing                 * val443;
  workpieceSetup                   * val444;
  std::list<workpieceSetup *>      * val445;
  workplan                         * val446;
  xorExpression                    * val447;
  char                             * sval;
  int                                ival;
  double                             rval;
}
/* Line 1489 of yacc.c.  */

	YYSTYPE;
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
# define YYSTYPE_IS_TRIVIAL 1
#endif

extern YYSTYPE yylval;

